services:
        redis:
                image: redis
        web-node:
                build: ./node
                depends_on:
                        - redis
        web-go:
                build: ./go
                depends_on:
                        - redis
        nginx:
                image: nginx
                depends_on:
                        - web-node
                        - web-go
                volumes:
                        - ./nginx/conf.d:/etc/nginx/conf.d
                        - ./nginx/html:/usr/share/nginx/html
                ports:
                        - "80:80"